<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>superfly-parent</artifactId>
        <groupId>com.payneteasy.superfly</groupId>
        <version>2.0-3-SNAPSHOT</version>
    </parent>
    <artifactId>superfly-client-ee8</artifactId>
    <name>Superfly Client Java EE 8</name>
    <description>Servlet filters, listeners and session adapter for Superfly client on Java EE 8 (javax.servlet)</description>

    <dependencies>
        <dependency>
            <groupId>com.payneteasy.superfly</groupId>
            <artifactId>superfly-client-core</artifactId>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
